export const environment = {
  production: true,
  apiUrlIns: 'https://app.linsoft.xyz:8081/api',
  apiUrlInsUpload: 'https://app.linsoft.xyz:8082/api',
  apiUrlCat: 'https://app.linsoft.xyz:8083/api',
  apiUrlCourse: 'https://app.linsoft.xyz:8084/api',
  apiUrlExamen: 'https://app.linsoft.xyz:8091/api',
  apiUrlSession: 'https://app.linsoft.xyz:8085/api',
  apiUrlSessionExamen: 'https://app.linsoft.xyz:8092/api',
  apiUrlPanningExamen: 'https://app.linsoft.xyz:8093/api',
  apiUrlFourniss: 'https://app.linsoft.xyz:8086/api',
  apiUrlPlanning: 'https://app.linsoft.xyz:8087/api',
  apiUrlDashboard: 'https://app.linsoft.xyz:8088/api',
  apiUrlDashboardExamen: 'https://app.linsoft.xyz:8094/api',
  apiUrlCompteFor: 'https://app.linsoft.xyz:8089/api',
  apiUrlCompteEx: 'https://app.linsoft.xyz:8095/api',
  apiUrlAuth: 'https://app.linsoft.xyz:8090/api',
  apiUrlUtilisateurs: 'https://app.linsoft.xyz:8096/api',
};
